/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String A = "assets/A.jpg";
  static const String doctor = "assets/Doctor.jpg";
  static const String doctor1 = "assets/doctor1.jpg";
  static const String doctor2 = "assets/doctor2.jpg";
  static const String doctor3 = "assets/doctor3.jpg";
  static const String doctor4 = "assets/doctor4.jpg";
  static const String download = "assets/download.jpg";
  static const String download1 = "assets/download1.png";
  static const String h = "assets/h.jpg";
  static const String images = "assets/images.jpg";
  static const String img = "assets/img.png";
  static const String j = "assets/j.webp";
  static const String k = "assets/k.jpg";
  static const String p = "assets/p.jpg";
  static const String p2 = "assets/p2.jpg";
  static const String photo = "assets/photo.jpg";
  static const String photo1 = "assets/photo1.jpg";
  static const String photo_1_2023_03_09_20_30_06 =
      "assets/photo_1_2023-03-09_20-30-06.jpg";
}
